comp2007-Assignment2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


//Remember this gets linked to the home folder

namespace comp2007_Assignment2.Controllers
{
  
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Us";

            return View();
        }

        public ActionResult Menu()
        {
            ViewBag.Message = "Menu-buy stuff.";

            return View();
        }

        public ActionResult MenuItemDetails()
        {
            ViewBag.Message = "Menu";

            return View();
        }

        public ActionResult Home()
        {
            ViewBag.Message = "Home";

            return View();
        }

        public ActionResult HomePage()
        {
            ViewBag.Message = "HomePage";

            return View();
        }




    }
}

comp2007-Assignment2/Controllers/itemsMenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using comp2007_Assignment2;



//This page is so I can create a table out of the database information

namespace comp2007_Assignment2.Controllers
{
    public class itemsMenusController : Controller
    {
        private sqlDataEntities1 db = new sqlDataEntities1();

        // GET: itemsMenus
        public ActionResult Index()
        {
            return View(db.itemsMenus.ToList());
        }

        // GET: itemsMenus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            itemsMenu itemsMenu = db.itemsMenus.Find(id);
            if (itemsMenu == null)
            {
                return HttpNotFound();
            }
            return View(itemsMenu);
        }

        // GET: itemsMenus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: itemsMenus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Item_name,Item_group,price,whatIs")] itemsMenu itemsMenu)
        {
            if (ModelState.IsValid)
            {
                db.itemsMenus.Add(itemsMenu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(itemsMenu);
        }

        // GET: itemsMenus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            itemsMenu itemsMenu = db.itemsMenus.Find(id);
            if (itemsMenu == null)
            {
                return HttpNotFound();
            }
            return View(itemsMenu);
        }

        // POST: itemsMenus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Item_name,Item_group,price,whatIs")] itemsMenu itemsMenu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemsMenu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemsMenu);
        }

        // GET: itemsMenus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            itemsMenu itemsMenu = db.itemsMenus.Find(id);
            if (itemsMenu == null)
            {
                return HttpNotFound();
            }
            return View(itemsMenu);
        }

        // POST: itemsMenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            itemsMenu itemsMenu = db.itemsMenus.Find(id);
            db.itemsMenus.Remove(itemsMenu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

comp2007-Assignment2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<!-- Brandon Roy, application is for an assinment as an e-commerce application-->
<p>Games* is a reatiler for pc gaming and electronics</p>

<img src="@Url.Content("~/Content/Images/companyLogo.png")" width="400" />

comp2007-Assignment2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<!--THis page is made for a customer to contact the business and know where its located-->
<!-- Brandon Roy, application is for an assinment as an e-commerce application-->

<address>
   1 Georgian Drive<br />
    Barrie, On<br />
    <abbr title="Phone">P:</abbr>
    7054444092
</address>

<address>
    <strong>Games*:</strong>   <a href="mailto:brandonroycstn@hotmail.com">brandonroycstn@example.com</a><br />
</address>




<img src="@Url.Content("~/Content/Images/map.png")" />

comp2007-Assignment2/Views/Home/Footer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <p>Brandon Roy :2016</p>
    </div>
</body>
</html>

comp2007-Assignment2/Views/Home/Header.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dragon Resteraunt</title>
</head>
<body>
    <div>

    
    </div>
</body>
</html>

comp2007-Assignment2/Views/Home/HomePage.cshtml
@{
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
   <!--THis is the landing page for my site, it has images and a menu button to bring it to the menu page-->
    <!-- Brandon Roy, application is for an assinment as an e-commerce application-->
 
</head>
<body>
    <div>

        

        <div class="jumbotron">
            <h1>Games*</h1>
            <p class="lead">Welcome to our site</p>
            <p class="lead">Click the button to go to our menu page</p>
            <p><a href="Menu" class="btn btn-primary btn-lg">Menu &raquo;</a></p>
        </div>

        <div class="row">
            <div class="col-md-4">
                <img src="@Url.Content("~/Content/Images/companyLogo.png")" width="400" />
              
            </div>
            </div>
        </div>


</body>
</html>

comp2007-Assignment2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

    
}



<!-- Brandon Roy, application is for an assinment as an e-commerce application-->

comp2007-Assignment2/Views/Home/Menu.cshtml
                @{
                            ViewBag.Title = "Menu";
                        }
                        <h2>@ViewBag.Title.</h2>




<!-- Brandon Roy, application is for an assinment as an e-commerce application-->

                        <div>
                            @Html.ActionLink("All Menu items", "Index", "itemsMenus")<br />

                        </div>

comp2007-Assignment2/Views/Home/MenuItemDetails.cshtml
@{
    ViewBag.Title = "MenuItemDetails";
}

<h2>MenuItemDetails</h2>



<!--I was not able to use this page beacuase I was not able to make a table because of an error. database.open would not work-->

comp2007-Assignment2/Views/Home/productDetails.cshtml
@{
    ViewBag.Title = "MenuItemDetails";
}

<h2>MenuItemDetails</h2>



<!--I was not able to use this page beacuase I was not able to make a table because of an error. database.open would not work-->